import home1 from "../assets/images/home/home1.jpg";
import home2 from "../assets/images/home/home2.jpg";
import home3 from "../assets/images/home/home3.jpg";
import home4 from "../assets/images/home/home4.jpg";
import home5 from "../assets/images/home/home5.jpg";
import home6 from "../assets/images/home/home6.jpg";

export const genders = ["Male", "Female"];

export const staticEmail = "ahmed@gmail.com";
export const staticPassword = "ahmed123";

export const events = [
  {
    id: 1,
    title: "Dinner with 27 Circle Hosts",
    location: "Alaska, US",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$12",
    discountedPrice: "$0",
    rating: 3.2,
    reviews: 91,
    image: home1,
  },
  {
    id: 2,
    title: "Dinner with 27 Circle Hosts",
    location: "Florida, US",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$12",
    discountedPrice: null,
    rating: 3.2,
    reviews: 91,
    image: home2,
  },
  {
    id: 3,
    title: "Dinner with 27 Circle Hosts",
    location: "Kansas, US",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$24",
    discountedPrice: null,
    rating: 3.2,
    reviews: 91,
    image: home3,
  },
  {
    id: 4,
    title: "Networking: Just Dinner",
    location: "Illinois, US",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$24",
    discountedPrice: null,
    rating: 3.2,
    reviews: 91,
    image: home4,
  },
  {
    id: 5,
    title: "Networking: Just Dinner",
    location: "Tanta, Egypt",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$24",
    discountedPrice: null,
    rating: 3.2,
    reviews: 91,
    image: home5,
  },
  {
    id: 6,
    title: "Networking: Just Dinner",
    location: "Cairo, Egypt",
    ageRange: "Ages 21-27",
    gender: "Gender",
    category: "Categories",
    date: "Jan. 25 at 7pm",
    price: "$24",
    discountedPrice: null,
    rating: 3.2,
    reviews: 91,
    image: home6,
  },
];

export const americanStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const notifications = [
  {
    id: 1,
    message: "Your Exotic Veggie Platter is on the menu. Get excited!",
    time: "2m",
  },
  {
    id: 2,
    message: "Today's the day. Your culinary adventure is almost there.",
    time: "51m",
  },
  {
    id: 3,
    message: "Last chance to add a little extra to your Tuesday delivery.",
    time: "2 days ago",
  },
  {
    id: 4,
    message: "Today's the day. Your culinary adventure is almost there.",
    time: "2 days ago",
  },
  {
    id: 5,
    message: "Your Exotic Veggie Platter is on the menu. Get excited!",
    time: "2 days ago",
  },
];
